# Generated by Django 3.2.25 on 2024-03-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom_tournois', models.CharField(max_length=100)),
                ('score_equipe', models.IntegerField()),
                ('score_equipe_adverse', models.IntegerField()),
                ('adversaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
